/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package org.example.exceptions;

/**
 *
 * @author Hans
 */
// Thrown when user provide object fields and values , that hsouldnt be provided with a request body JSON object for an endpoint with a POST method
// eg - POST bookstore/api/customers  - customerID shouldnt be provided as it is auto generated by the server 
public class UnauthorizedFieldAssignmentException extends RuntimeException{

    public UnauthorizedFieldAssignmentException(String message) {
        
        super(message);
        
    }
    
    
    
}
